version: "3.5"

services:
  frontend_server:
    image: frontend2
    build: 
      context: .
      dockerfile: Dockerfile
      args: 
        - BACKEND_URL=$REACT_APP_BACKEND
    ports:
      - 3000:3000
    container_name: reading-list-frontend

  reverse_proxy:
    image: nginx:1.19-alpine
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    environment:
      - NGINX_PORT=80
