version: "3.5"

services:
  frontend_server:
    image: frontend
    build: .
    ports:
      - 3000:3000
    container_name: reading-list-frontend

  reverse_proxy:
    image: nginx:1.19-alpine
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    environment:
      - NGINX_PORT=80
